### ISSUE TITLE
paper正文是否可以提供

### ISSUE THREAD

**Issue by thinksee** [Mauriyin/FLDRL-in-Wireless-Communication#11]
我search了google学术、ieee等论文检索平台，没有找到相应的论文，请问是否可以提供相应的论文或者arxiv地址

**Comment by Davidcheng999817** [comment]
我也找不到，请问楼主找到否

**Comment by Mauriyin** [comment]
VTC会议官方一直没有更新，如果需要的话可以邮件联系我，我可以发送draft版本给大家。
