### ISSUE TITLE
Paper Not exist 

### ISSUE THREAD

**Issue by Abdullatif2** [Mauriyin/FLDRL-in-Wireless-Communication#12]
I tried to find the related paper mentioned in your code but I couldn't find it. Could you please share your paper draft.

**Comment by Mauriyin** [comment]
It seems that the IEEE takes a long time to publish the proceedings, so I will put it on arXiv.

**Comment by Mauriyin** [comment]
The paper can be found on arxiv: https://arxiv.org/abs/2102.07019

**Comment by Mauriyin** [comment]
https://ieeexplore.ieee.org/document/9348485
