### ISSUE TITLE
Reg  requirements.txt  

### ISSUE THREAD

**Issue by akramIOT** [Mauriyin/FLDRL-in-Wireless-Communication#13]
Hi  Mauriyin,
                       Can you share the  requirements.txt  and  the  CUDA  dependency for  using this  project  ?.
Kindly  find  my error  below.

(RLDL_WIFI) C:\Users\isheriff\PycharmProjects\pythonProject1\FLDRL-in-Wireless-Communication>python test_CSMA_DQN_withModelAllocation.py
Traceback (most recent call last):
  File "test_CSMA_DQN_withModelAllocation.py", line 15, in <module>
    cfg = Config()
  File "C:\Users\isheriff\PycharmProjects\pythonProject1\FLDRL-in-Wireless-Communication\config.py", line 54, in __init__
    torch.cuda.set_device(self.main_gpu_id)
  File "C:\Users\isheriff\Anaconda3\envs\RLDL_WIFI\lib\site-packages\torch\cuda\__init__.py", line 261, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

(RLDL_WIFI) C:\Users\isheriff\PycharmProjects\pythonProject1\FLDRL-in-Wireless-Communication> python setup.py clean
python: can't open file 'setup.py': [Errno 2] No such file or directory

(RLDL_WIFI) C:\Users\isheriff\PycharmProjects\pythonProject1\FLDRL-in-Wireless-Communication>python setup.py clean
python: can't open file 'setup.py': [Errno 2] No such file or directory

(RLDL_WIFI) C:\Users\isheriff\PycharmProjects\pythonProject1\FLDRL-in-Wireless-Communication>conda install pytorch=1.3.1 torchvision=0.4.2 -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - torchvision=0.4.2 -> python[version='>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package zlib conflicts for:
torchvision=0.4.2 -> pillow[version='>=4.1.1'] -> zlib[version='>=1.2.11,<1.3.0a0']
python=3.8 -> sqlite[version='>=3.33.0,<4.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']The following specifications were found to be incompatible with your CUDA driver:

  - feature:/win-64::__cuda==11.0=0
  - feature:|@/win-64::__cuda==11.0=0

Your installed CUDA driver is: 11.0

(RLDL_WIFI) C:\Users\isheriff\PycharmProjects\pythonProject1\FLDRL-in-Wireless-Communication>

**Comment by Mauriyin** [comment]
Here is some information from my device:
- Cuda compilation tools, release 10.1, V10.1.243
- matplotlib==3.2.0
torch==1.3.1
numpy==1.18.5
tqdm==4.43.0

**Comment by akramIOT** [comment]
Thanks  Mauriyin, this  pip install  resolved my issue  

pip install torch==1.5.0+cu101 torchvision==0.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
