### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by Oreki-PJ** [Mauriyin/FLDRL-in-Wireless-Communication#15]
Hello! I download this whole code. However, when I run test_CSMA_DQN_withModelAllocation.py, I do not found the "tqdm", and it says error. So can you help me?

**Comment by Mauriyin** [comment]
Hi, 
Please check here for the installation of tqdm:  
https://pypi.org/project/tqdm/

**Comment by Oreki-PJ** [comment]
got it! Thanks a lot!
